dist: trusty
language: node_js
node_js:
  - lts/*
  - node
cache: yarn
install:
  - yarn && cd frontend && yarn && cd - && cd backend && yarn && cd -
script:
  - yarn lint
  - yarn build
  # - yarn test
