apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"20"},"creationTimestamp":"2019-11-09T17:58:37Z","generation":20,"labels":{"app":"postgres"},"name":"postgres","namespace":"dragon-go","resourceVersion":"721267","selfLink":"/apis/apps/v1/namespaces/dragon-go/deployments/postgres","uid":"794410d0-2e33-4962-a3ad-fa4a37b739e1"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"postgres"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"postgres"}},"spec":{"containers":[{"args":["-c","listen_addresses=*"],"env":[{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"postgres-secret"}}}],"image":"sirwojtek/postgres:latest","name":"postgres","ports":[{"containerPort":5432,"name":"postgres","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/postgresql/data","name":"postgres-persistent-storage"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"postgres-persistent-storage","persistentVolumeClaim":{"claimName":"postgres-pv-claim"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2019-11-13T15:44:20Z","lastUpdateTime":"2019-11-15T11:23:25Z","message":"ReplicaSet \"postgres-74c99dff45\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2019-11-15T14:13:54Z","lastUpdateTime":"2019-11-15T14:13:54Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":20,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2019-11-15T14:45:34Z"
  generation: 1
  labels:
    app: postgres
  name: postgres
  namespace: dragon-go
  resourceVersion: "726227"
  selfLink: /apis/apps/v1/namespaces/dragon-go/deployments/postgres
  uid: cce4322a-e48a-4d51-876c-d201a1c07fae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        image: sirwojtek/postgres:latest
        imagePullPolicy: Always
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-11-15T14:45:34Z"
    lastUpdateTime: "2019-11-15T14:45:36Z"
    message: ReplicaSet "postgres-66c76f64dc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-11-15T15:05:36Z"
    lastUpdateTime: "2019-11-15T15:05:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
